server:
  port: 8085
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    health:
      show-details: always

internal:
  api:
    shopping-service:
      url: http://shopping-service:8084/shopping/cart

spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: order
      username: order-service
      password: Password123!

logging:
  level:
    root: INFO
    com.example.orderservice: DEBUG